# Generated by Django 5.2.4 on 2025-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('Teacher', 'Teacher'), ('Head of Department', 'Head of Department'), ('Principal', 'Principal'), ('Administrator', 'Administrator')], max_length=30)),
                ('subjects', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('security_question', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
