# Generated by Django 5.2.4 on 2025-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='security_question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
